name: Deploy frontend to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & push frontend Docker image
      env:
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        BACKEND_HTTP_URL: ${{ secrets.BACKEND_HTTP_URL }}
        BACKEND_WS_URL: ${{ secrets.BACKEND_WS_URL }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tetris
        IMAGE_TAG: frontend
      run: |
        cd frontend
        docker build --build-arg FRONTEND_URL=$FRONTEND_URL --build-arg BACKEND_HTTP_URL=$BACKEND_HTTP_URL --build-arg BACKEND_WS_URL=$BACKEND_WS_URL -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
